apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: workloads
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
commonLabels:
  app: connect-demo-website
  backstage.io/kubernetes-id: connect-demo-website
images:
  - name: to-be-replaced
    newName: ghcr.io/nicpym/connect-demo-website
    newTag: v0.0.1
